project:
  type: website

website:
  title: "E155Project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: bill.qmd
        text: DOCUMENTATION
      - href: mcuD.qmd
        text: MCU DESIGN
      - href: fpgaD.qmd
        text: FPGA DESIGN
      - href: results.qmd
        text: RESULTS
      - href: ai.qmd
        text: AI USE
      - href: reference.qmd
        text: ACK/REF
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

