project:
  type: website

website:
  title: "E155Project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: bill.qmd
        text: Documentation

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

