project:
  type: website

website:
  title: "E155Project"
  navbar:
    left:
      - href: home.qmd
        text: Home

format:
  html:
    theme:
      - darkly
      - brand
    css: styles.css
    toc: true

